### ISSUE TITLE
Extend HTML syntax instead of "overwriting"

### ISSUE THREAD

**Issue by princemaple** [princemaple/ngx-html-syntax#22]
Investigate how to take advantage of ST4 goodies, so we don't have to keep updating this whenever ST4 default HTML updates.

Possible resources:
- [JSX](https://github.com/sublimehq/Packages/blob/master/JavaScript/JSX.sublime-syntax)
- [Rails](https://github.com/sublimehq/Packages/blob/master/Rails/HTML%20(Rails).sublime-syntax)

**Comment by deathaxe** [comment]
It's not too difficult. _Rails_ is not an good start for investigation though. It uses the old `with_prototype` approach.

You may want to have a look at https://github.com/sublimehq/Packages/pull/2439 instead. It is a very simple example of how to add support for more tags by inheriting the `tag` object of the basic html.sublime-syntax.

The same would work well with `tag-attributes`. You just need to add something as:

```
contexts:

...

  tag-attributes:
    - meta_prepand: true
    - include: tag-ng-template-attribute
    - include: tag-ng-reference-attribute
    - include: tag-ng-bind-attribute
    - include: tag-ng-on-attribute
    - include: tag-ng-bindon-attribute

...
```

Same for your `interpolation` section. It might need to be included into extended contexts, which support angular interpolation.

Maybe we need to modify basic HTML a bit to support inheritance better. One first approach to do that is https://github.com/sublimehq/Packages/pull/2435
